ITSupport/ITSupport/Models/Topic.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITSupport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Topic()
        {
            this.Course = new HashSet<Course>();
        }
    
        public int IDTopic { get; set; }
        public string NameTopic { get; set; }
        public string Describe { get; set; }
        public string Images { get; set; }
        public Nullable<int> IDCreator { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ACourse ACourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Course { get; set; }
    }
}

ITSupport/ITSupport/Areas/Admin/Controllers/TopicController.cs
using ITSupport.Models;
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace ITSupport.Areas.Admin.Controllers
{
    public class TopicController : Controller
    {
        ITSupportEntities data = new ITSupportEntities();
        // GET: Admin/Course
        public ActionResult Index(int? page)
        {
            int iPageNum = (page ?? 1);
            int iPageSize = 7;
            return View(data.Topic.ToList().OrderBy(n => n.IDTopic).ToPagedList(iPageNum, iPageSize));
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.IDCreator = new SelectList(data.ACourse.ToList().OrderBy(n => n.Role), "IDCreator", "Role");
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Topic topic, FormCollection f, HttpPostedFileBase fFileUpload)
        {
            ViewBag.IDCreator = new SelectList(data.ACourse.ToList().OrderBy(n => n.Role), "IDCreator", "Role");

            if (fFileUpload == null)
            {
                ViewBag.ThongBao = "Hay chon anh bia";
                ViewBag.TenSach = f["sTenSach"];
                ViewBag.MoTa = f["sMoTa"];
                ViewBag.IDCreator = new SelectList(data.ACourse.ToList().OrderBy(n => n.Role), "IDCreator", "Role", int.Parse(f["IDCreator"]));
                return View();
            }
            else
            {
                if (ModelState.IsValid)
                {
                    var sFileName = Path.GetFileName(fFileUpload.FileName);
                    var path = Path.Combine(Server.MapPath("~/Asset/Image/Topic"), sFileName);
                    if (!System.IO.File.Exists(path))
                    {
                        fFileUpload.SaveAs(path);
                    }
                    topic.NameTopic = f["sTenSach"];
                    topic.Describe = f["sMoTa"].Replace("<p>", "").Replace("</p>", "/n");
                    topic.Images = sFileName;
                    topic.CreateDate = Convert.ToDateTime(f["dNgayCapNhat"]);
                    data.Topic.Add(topic);
                    data.SaveChanges();
                }
                return View();
            }
        }

        public ActionResult Details(int id)
        {
            var topic = data.Topic.SingleOrDefault(n => n.IDTopic == id);
            if (topic == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(topic);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var topic = data.Topic.SingleOrDefault(n => n.IDTopic == id);
            if (topic == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(topic);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirm(int id, FormCollection f)
        {
            var topic = data.Topic.SingleOrDefault(n => n.IDTopic == id);
            if (topic == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            var acourse = (data.Topic.Where(vs => vs.IDTopic == id)).SingleOrDefault();
            if (acourse != null)
            {
                data.Topic.Remove(acourse);
                data.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var topic = data.Topic.SingleOrDefault(n => n.IDTopic == id);
            if (topic == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.Creator = new SelectList(data.ACourse.ToList().OrderBy(n => n.Role), "IDCreator", "Role", topic.IDCreator);
            return View(topic);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(FormCollection f, HttpPostedFileBase fFileUpload)
        {
            var iMaSach = int.Parse(f["iMaSach"]);
            var topic = data.Topic.SingleOrDefault(n => n.IDTopic == iMaSach);

            if (ModelState.IsValid)
            {
                if (fFileUpload != null)
                {
                    var sFileName = Path.GetFileName(fFileUpload.FileName);
                    var path = Path.Combine(Server.MapPath("~/Asset/Image/Topic"), sFileName);
                    if (!System.IO.File.Exists(path))
                    {
                        fFileUpload.SaveAs(path);
                    }
                    topic.Images = sFileName;
                }
                topic.NameTopic = f["sTenSach"];
                topic.Describe = f["sMoTa"].Replace("<p>", "").Replace("</p>", "\n");
                topic.ModifiedDate = Convert.ToDateTime(f["dNgaySuaDoi"]);
                data.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(topic);
        }
    }
}

ITSupport/ITSupport/Areas/Admin/Views/Topic/Create.cshtml
@model ITSupport.Models.Topic

@{
    ViewBag.Title = "Thêm Chủ Đề Khóa Học";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


<h2>THÊM CHỦ ĐỀ KHÓA HỌC MỚI</h2>

@*Thêm thuộc tính cho form để upload ảnh *@
@using (Html.BeginForm("Create", "Topic", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">
                Tên Khóa Học:
            </label>
            <div class="col-md-10">
                <input type="text" size="70" name="sTenSach" value="@ViewBag.TenSach" required />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">
                Mô tả:
            </label>
            <div class="col-md-10">
                <textarea name="sMoTa">
                        @ViewBag.MoTa
                </textarea>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">
                Ảnh bìa:
            </label>
            <div class="col-md-10">
                <input type="file" name="fFileUpload" />
                @*Thông báo lỗi yêu cầu phải chọn ảnh bìa*@
                @ViewBag.ThongBao
            </div>
        </div>
        <div class="form-group">

            <label class="control-label col-md-2">
                Ngày cập nhật:
            </label>
            <div class="col-md-10">
                <input type="date" name="dNgayCapNhat" required />
            </div>
        </div>
        <div class="form-group">

            <label class="control-label col-md-2">
                Người Tạo:
            </label>
            <div class="col-md-10">
                @*Hiển thị ViewBag.MaCD vào dropdownlist*@
                @Html.DropDownList("IDCreator")
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm mới" class="btn btn-secondary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("VỀ TRANG QUẢN LÝ SÁCH", "Index")
</div>

ITSupport/ITSupport/Areas/Admin/Views/Topic/Delete.cshtml
@model ITSupport.Models.Topic

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<style type="text/css">
    img {
        width: 200px;
        margin-bottom: 20px;
    }

    h3, h4 {
        color: red;
        font-weight: bold;
    }
</style>
<h2> XÁC NHẬN THÔNG TIN CẦN XÓA</h2>
<h3>Bạn quyết định xóa quyển sách này?</h3>
<h4>@Html.Raw(ViewBag.ThongBao)</h4>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên sách:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NameTopic)
        </dd>
        <dt>
            Mô tả:
        </dt>
        <dd>
            @Html.Raw(@Model.Describe.ToString().Replace("\n", "</p><p>&nbsp&nbsp&nbsp&nbsp&nbsp"))
        </dd>
        <dt>
            Ảnh bìa:
        </dt>
        <dd>
            <img src="~/Asset/Image/Topic/@Model.Images" alt=" @Model.NameTopic">
        </dd>
        <dt>
            Ngày cập nhật:
        </dt>
        <dd>
            @Html.FormatValue(@Model.CreateDate, "{0:dd/MM/yyyy}")
        </dd>
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            <input type="submit" value="XÓA" class="btn btn-danger" /> |
            @Html.ActionLink("VỀ TRANG QUẢN LÝ SÁCH", "Index")
        </div>
    }
</div>

ITSupport/ITSupport/Areas/Admin/Views/Topic/Details.cshtml
@model ITSupport.Models.Topic

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<style type="text/css">
    img {
        width: 200px;
        margin-bottom: 20px;
    }
</style>
<h2 style="text-align:center">
    Chi Tiết Khóa Học
</h2>
<div style="text-align:center">
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên khóa học:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NameTopic)
        </dd>
        <dt>
            Mô tả:
        </dt>
        <dd>
            @Html.Raw(@Model.Describe.ToString().Replace("\n", "</p><p>&nbsp&nbsp&nbsp&nbsp&nbsp"))
        </dd>
        <dt>
            Ảnh bìa:
        </dt>
        <dd>
            <img src="~/Asset/Image/Topic/@Model.Images" alt=" @Model.NameTopic">
        </dd>
        <dt>
            Ngày cập nhật:
        </dt>
        <dd>
            @Html.FormatValue(@Model.CreateDate, "{0:dd/MM/yyyy}")
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.IDTopic }) |
    @Html.ActionLink("VỀ TRANG QUẢN LÝ SÁCH", "Index")
</p>

ITSupport/ITSupport/Areas/Admin/Views/Topic/Edit.cshtml
@model ITSupport.Models.Topic

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<h2> ĐIỀU CHỈNH THÔNG TIN SÁCH</h2>
@*Thêm thuộc tính cho form để upload ảnh *@
@using (Html.BeginForm("Edit", "Topic", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{@Html.AntiForgeryToken()
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <label class="control-label col-md-2">
            Mã sách:
        </label>
        <div class="col-md-10">
            @*Chỉ hiển thị mã sách không cho sửa*@
            <input type="text" size="70" name="iMaSach" value="@Model.IDTopic" readonly />
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">
            Tên sách:
        </label>
        <div class="col-md-10">
            <input type="text" size="70" name="sTenSach" value="@Model.NameTopic" required />
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">
            Mô tả:
        </label>
        <div class="col-md-10">
            <textarea name="sMoTa">
            <p>@Model.Describe.Replace("\n", "<p></p>")</p>
            </textarea>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">
            Ảnh bìa:
        </label>
        <div class="col-md-10">
            <input type="file" name="fFileUpload" />
            <img src="~/Asset/Images/Topic/@Model.Images" width="120">
            (Ảnh hiện tại)
        </div>
    </div>
    <div class="form-group">

        <label class="control-label col-md-2">
            Ngày sửa đổi:
        </label>
        <div class="col-md-10">
            <input type="date" name="dNgaySuaDoi" required />
        </div>
    </div> <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="LƯU THÔNG TIN" class="btn btn-success" />
        </div>
    </div>
</div>
}
<div>
    @Html.ActionLink("VỀ TRANG QUẢN LÝ SÁCH", "Index")
</div>

ITSupport/ITSupport/Areas/Admin/Views/Topic/Index.cshtml
@using ITSupport.Models
@using PagedList.Mvc
@model PagedList.PagedList<ITSupport.Models.Topic>

@helper Truncate(string input, int length)
{
    if (input.Length <= length)
    {
        @Html.Raw(input)
    }
    else
    {
        var thisString = input.Substring(0, length);
        @Html.Raw(thisString)
    }
}

@{
    ViewBag.Title = "Quản Lý Thông Tin Khóa Học";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


<h2 style="text-align: center" class="bigTitle animationTop delay-15">QUẢN LÝ THÔNG TIN KHÓA HỌC</h2>

<p>
    @Html.ActionLink("Thêm mới", "Create")
</p>
<table class="table">
    <tr>
        <th style="text-align:center;width:140px">
            Tên Chủ Đề
        </th>
        <th style="text-align:center;width:200px">
            Mô tả
        </th>
        <th style="text-align:center;width:80px">
            Hình minh hoạ
        </th>
        <th style="text-align:center;width:100px">
            Ngày Tạo
        </th>
        <th style="text-align:center;width:80px">
            Người Tạo
        </th>
        <th style="text-align:center;width:100px">
            Ngày Sửa đổi
        </th>
        <th style="text-align:center">
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <td>
                @*Sử dụng helper để cắt TenSach lấy 50 ký tự*@
                @Truncate(item.NameTopic, 50)
            </td>

            <td>
                @*Sử dụng helper để cắt MoTa lấy 70 ký tự*@
                @Html.Raw(Truncate(item.Describe, 70).ToString())
            </td>
            <td>
                <img src="~/Asset/Image/Topic/@item.Images" asp-append-version="true" style="width: 50px;" />
            </td>
            <td>
                @*Định dạng hiển thị*@
                @Html.FormatValue(@item.CreateDate, "{0:dd/MM/yyyy}")
            </td>
            <td>
                @*Định dạng hiển thị*@
                @*@Truncate(item.CreateBy, 50)*@
                @Html.DisplayFor(modelItem => item.ACourse.Role)
            </td>
            <td>
                @Html.FormatValue(@item.ModifiedDate, "{0:dd/MM/yyyy}")
            </td>

            <td>
                <a href="@Url.Action("Edit", new { id = item.IDTopic })" class="btn btn-warning" role="button">Sửa</a>
                <a href="@Url.Action("Details", new { id = item.IDTopic })" class="btn btn-primary" role="button">Chi tiết</a>
                <a href="@Url.Action("Delete", new { id = item.IDTopic })" class="btn btn-danger" role="button">Xóa</a>
            </td>
        </tr>
    }
</table>

@*Tạo iên kết phần trang
            Trang @(Model.PageCount < Model.PageNumber ? 0 :
    Model.PageNumber)/@Model.PageCount
    <div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
    </div>
    <style>
        .MenuTrang {
            display: inline;
            text-align: center;
        }
    </style>
*@