ITSupport/Models/Course.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITSupport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.CourseQuestion = new HashSet<CourseQuestion>();
            this.Lesson1 = new HashSet<Lesson>();
            this.TestSession = new HashSet<TestSession>();
        }
    
        public long IDCourse { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Saleprice { get; set; }
        public string Describe { get; set; }
        public string Images { get; set; }
        public Nullable<int> IDCreator { get; set; }
        public Nullable<int> IDTopic { get; set; }
        public Nullable<int> IDPH { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> TestTime { get; set; }
        public Nullable<long> IDLesson { get; set; }
    
        public virtual ACourse ACourse { get; set; }
        public virtual Lesson Lesson { get; set; }
        public virtual PublishingHouse PublishingHouse { get; set; }
        public virtual Topic Topic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseQuestion> CourseQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lesson> Lesson1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestSession> TestSession { get; set; }
    }
}

ITSupport/Areas/Admin/Controllers/CourseController.cs
using ITSupport.Models;
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace ITSupport.Areas.Admin.Controllers
{
    public class CourseController : Controller
    {
        ITSupportEntities data = new ITSupportEntities();
        // GET: Admin/Course
        public ActionResult Index(int? page)
        {
            int iPageNum = (page ?? 1);
            int iPageSize = 7;
            return View(data.Course.ToList().OrderBy(n => n.IDCourse).ToPagedList(iPageNum, iPageSize));
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.IDTopic = new SelectList(data.Topic.ToList().OrderBy(n => n.NameTopic), "IDTopic", "NameTopic");
            ViewBag.IDPH = new SelectList(data.PublishingHouse.ToList().OrderBy(n => n.NamePH), "IDPH", "NamePH");
            ViewBag.IDCreator = new SelectList(data.ACourse.ToList().OrderBy(n => n.Role), "IDCreator", "Role");
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Course course, FormCollection f, HttpPostedFileBase fFileUpload)
        {
            ViewBag.IDTopic = new SelectList(data.Topic.ToList().OrderBy(n => n.NameTopic), "IDTopic", "NameTopic");
            ViewBag.IDPH = new SelectList(data.PublishingHouse.ToList().OrderBy(n => n.NamePH), "IDPH", "NamePH");
            ViewBag.IDCreator = new SelectList(data.ACourse.ToList().OrderBy(n => n.Role), "IDCreator", "Role");

            if (fFileUpload == null)
            {
                ViewBag.ThongBao = "Hay chon anh bia";
                ViewBag.TenSach = f["sTenSach"];
                ViewBag.MoTa = f["sMoTa"];
                ViewBag.IDTopic = new SelectList(data.Topic.ToList().OrderBy(n => n.NameTopic), "IDTopic", "NameTopic", int.Parse(f["IDTopic"]));
                ViewBag.IDPH = new SelectList(data.PublishingHouse.ToList().OrderBy(n => n.NamePH), "IDPH", "NamePH", int.Parse(f["IDPH"]));
                ViewBag.IDCreator = new SelectList(data.ACourse.ToList().OrderBy(n => n.Role), "IDCreator", "Role", int.Parse(f["IDCreator"]));
                return View();
            }
            else
            {
                if (ModelState.IsValid)
                {
                    var sFileName = Path.GetFileName(fFileUpload.FileName);
                    var path = Path.Combine(Server.MapPath("~/Asset/Image"), sFileName);
                    if (!System.IO.File.Exists(path))
                    {
                        fFileUpload.SaveAs(path);
                    }
                    course.Name = f["sTenSach"];
                    course.Describe = f["sMoTa"].Replace("<p>", "").Replace("</p>", "/n");
                    course.Images = sFileName;
                    course.CreateDate = Convert.ToDateTime(f["dNgayCapNhat"]);
                    course.IDTopic = int.Parse(f["IDTopic"]);
                    course.IDPH = int.Parse(f["IDPH"]);
                    data.Course.Add(course);
                    data.SaveChanges();
                }
                return View();
            }
        }

        public ActionResult Details(int id)
        {
            var course = data.Course.SingleOrDefault(n => n.IDCourse == id);
            if (course == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(course);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var course = data.Course.SingleOrDefault(n => n.IDCourse == id);
            if (course == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(course);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirm(int id, FormCollection f)
        {
            var course = data.Course.SingleOrDefault(n => n.IDCourse == id);
            if (course == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            var acourse = (data.Course.Where(vs => vs.IDCourse == id)).SingleOrDefault();
            if (acourse != null)
            {
                data.Course.Remove(acourse);
                data.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var course = data.Course.SingleOrDefault(n => n.IDCourse == id);
            if (course == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.MaCD = new SelectList(data.Topic.ToList().OrderBy(n => n.NameTopic), "IDTopic", "NameTopic", course.IDTopic);
            ViewBag.MaNXB = new SelectList(data.PublishingHouse.ToList().OrderBy(n => n.NamePH), "IDPH", "NamePH", course.IDPH);
            ViewBag.Creator = new SelectList(data.ACourse.ToList().OrderBy(n => n.Role), "IDCreator", "Role", course.IDCreator);
            return View(course);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(FormCollection f, HttpPostedFileBase fFileUpload)
        {
            var iMaSach = int.Parse(f["iMaSach"]);
            var course = data.Course.SingleOrDefault(n => n.IDCourse == iMaSach);
            ViewBag.MaCD = new SelectList(data.Topic.ToList().OrderBy(n => n.NameTopic), "IDTopic", "NameTopic", course.IDTopic);
            ViewBag.MaNXB = new SelectList(data.PublishingHouse.ToList().OrderBy(n => n.NamePH), "IDPH", "NamePH", course.IDPH);
            ViewBag.Creator = new SelectList(data.ACourse.ToList().OrderBy(n => n.Role), "IDCreator", "Role", course.IDCreator);

            if (ModelState.IsValid)
            {
                if (fFileUpload != null)
                {
                    var sFileName = Path.GetFileName(fFileUpload.FileName);
                    var path = Path.Combine(Server.MapPath("~/Asset/Image"), sFileName);
                    if (!System.IO.File.Exists(path))
                    {
                        fFileUpload.SaveAs(path);
                    }
                    course.Images = sFileName;
                }
                course.Name = f["sTenSach"];
                course.Describe = f["sMoTa"].Replace("<p>", "").Replace("</p>", "\n");
                course.ModifiedDate = Convert.ToDateTime(f["dNgaySuaDoi"]);
                course.IDTopic = int.Parse(f["MaCD"]);
                course.IDPH = int.Parse(f["MaNXB"]);
                data.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(course);
        }
    }
}

ITSupport/Controllers/CourseController.cs
using ITSupport.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;

namespace ITSupport.Controllers
{
    public class CourseController : Controller
    {
        // GET: Course
        ITSupportEntities data = new ITSupportEntities();
        public ActionResult Index(int? page)
        {
            int iPageNum = (page ?? 1);
            int iPageSize = 4;
            return View(data.Topic.ToList().OrderBy(n => n.IDTopic).ToPagedList(iPageNum, iPageSize));

        }

        public ActionResult Excel()
        {
            // Lấy danh sách tất cả các chương từ bảng Course
            var chapters = data.Course.ToList();

            // Lọc danh sách các chương có khóa học tương ứng với Excel
            var excelChapters = chapters.Where(c => c.IDTopic == 3).ToList();

            // Lấy tên của chủ đề Excel từ bảng Topic
            var topic = data.Topic.FirstOrDefault(t => t.IDTopic == 3);

            // Truyền tên chủ đề vào Model để hiển thị trên View
            ViewBag.TopicName = topic.NameTopic;

            return View(excelChapters);
        }

        public ActionResult Word()
        {
            // Lấy danh sách tất cả các chương từ bảng Course
            var chapters = data.Course.ToList();

            // Lọc danh sách các chương có khóa học tương ứng với Excel
            var excelChapters = chapters.Where(c => c.IDTopic == 1).ToList();

            // Lấy tên của chủ đề Excel từ bảng Topic
            var topic = data.Topic.FirstOrDefault(t => t.IDTopic == 1);

            // Truyền tên chủ đề vào Model để hiển thị trên View
            ViewBag.TopicName = topic.NameTopic;

            return View(excelChapters);
        }

        public ActionResult PowerPoint()
        {
            // Lấy danh sách tất cả các chương từ bảng Course
            var chapters = data.Course.ToList();

            // Lọc danh sách các chương có khóa học tương ứng với Excel
            var excelChapters = chapters.Where(c => c.IDTopic == 6).ToList();

            // Lấy tên của chủ đề Excel từ bảng Topic
            var topic = data.Topic.FirstOrDefault(t => t.IDTopic == 6);

            // Truyền tên chủ đề vào Model để hiển thị trên View
            ViewBag.TopicName = topic.NameTopic;

            return View(excelChapters);
        }

    }
}

ITSupport/Areas/Admin/Views/Course/Create.cshtml
@model ITSupport.Models.Course
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>THÊM KHÓA HỌC MỚI</h2>

@*Thêm thuộc tính cho form để upload ảnh *@
@using (Html.BeginForm("Create", "Course", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">
                Tên Khóa Học:
            </label>
            <div class="col-md-10">
                <input type="text" size="70" name="sTenSach" value="@ViewBag.TenSach" required />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">
                Mô tả:
            </label>
            <div class="col-md-10">
                <textarea name="sMoTa">
                        @ViewBag.MoTa
                </textarea>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">
                Ảnh bìa:
            </label>
            <div class="col-md-10">
                <input type="file" name="fFileUpload" />
                @*Thông báo lỗi yêu cầu phải chọn ảnh bìa*@
                @ViewBag.ThongBao
            </div>
        </div>
        <div class="form-group">

            <label class="control-label col-md-2">
                Ngày cập nhật:
            </label>
            <div class="col-md-10">
                <input type="date" name="dNgayCapNhat" required />
            </div>
        </div>
        <div class="form-group">

            <label class="control-label col-md-2">
                Người Tạo:
            </label>
            <div class="col-md-10">
                @*Hiển thị ViewBag.MaCD vào dropdownlist*@
                @Html.DropDownList("IDCreator")
            </div>
        </div>
        <div class="form-group">

            <label class="control-label col-md-2">
                Khóa Học:
            </label>
            <div class="col-md-10">
                @*Hiển thị ViewBag.MaCD vào dropdownlist*@
                @Html.DropDownList("IDTopic")
            </div>
        </div>
        <div class="form-group">

            <label class="control-label col-md-2">
                Nhà Hợp Tác:
            </label>
            <div class="col-md-10">
                @Html.DropDownList("IDPH")
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm mới" class="btn btn-secondary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("VỀ TRANG QUẢN LÝ SÁCH", "Index")
</div>

ITSupport/Areas/Admin/Views/Course/Delete.cshtml
@model ITSupport.Models.Course

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<style type="text/css">
    img {
        width: 200px;
        margin-bottom: 20px;
    }

    h3, h4 {
        color: red;
        font-weight: bold;
    }
</style>
<h2> XÁC NHẬN THÔNG TIN CẦN XÓA</h2>
<h3>Bạn quyết định xóa quyển sách này?</h3>
<h4>@Html.Raw(ViewBag.ThongBao)</h4>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên sách:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            Mô tả:
        </dt>
        <dd>
            @Html.Raw(@Model.Describe.ToString().Replace("\n", "</p><p>&nbsp&nbsp&nbsp&nbsp&nbsp"))
        </dd>
        <dt>
            Ảnh bìa:
        </dt>
        <dd>
            <img src="~/Asset/Image/@Model.Images" alt=" @Model.Images">
        </dd>
        <dt>
            Ngày cập nhật:
        </dt>
        <dd>
            @Html.FormatValue(@Model.CreateDate, "{0:dd/MM/yyyy}")
        </dd>
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            <input type="submit" value="XÓA" class="btn btn-danger" /> |
            @Html.ActionLink("VỀ TRANG QUẢN LÝ SÁCH", "Index")
        </div>
    }
</div>

ITSupport/Areas/Admin/Views/Course/Details.cshtml
@model ITSupport.Models.Course
@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<style type="text/css">
    img {
        width: 200px;
        margin-bottom: 20px;
    }
</style>
<h2 style="text-align:center">
    Chi Tiết Khóa Học
</h2>
<div style="text-align:center">
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên khóa học:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            Mô tả:
        </dt>
        <dd>
            @Html.Raw(@Model.Describe.ToString().Replace("\n", "</p><p>&nbsp&nbsp&nbsp&nbsp&nbsp"))
        </dd>
        <dt>
            Ảnh bìa:
        </dt>
        <dd>
            <img src="~/Asset/Image/@Model.Images" alt=" @Model.Name">
        </dd>
        <dt>
            Ngày cập nhật:
        </dt>
        <dd>
            @Html.FormatValue(@Model.CreateDate, "{0:dd/MM/yyyy}")
        </dd>
        <dt>
            Khóa Học:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Topic.NameTopic)
        </dd>
        <dt>
            Nhà Hợp Tác:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PublishingHouse.NamePH)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.IDCourse }) |
    @Html.ActionLink("VỀ TRANG QUẢN LÝ SÁCH", "Index")
</p>

ITSupport/Areas/Admin/Views/Course/Edit.cshtml
@model ITSupport.Models.Course

@{ ViewBag.Title = "Edit"; Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<h2> ĐIỀU CHỈNH THÔNG TIN SÁCH</h2>
@*Thêm thuộc tính cho form để upload ảnh *@
@using (Html.BeginForm("Edit", "Course", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{@Html.AntiForgeryToken()
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <label class="control-label col-md-2">
            Mã sách:
        </label>
        <div class="col-md-10">
            @*Chỉ hiển thị mã sách không cho sửa*@
            <input type="text" size="70" name="iMaSach" value="@Model.IDCourse" readonly />
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">
            Tên sách:
        </label>
        <div class="col-md-10">
            <input type="text" size="70" name="sTenSach" value="@Model.Name" required />
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">
            Mô tả:
        </label>
        <div class="col-md-10">
            <textarea name="sMoTa">
            <p>@Model.Describe.Replace("\n", "<p></p>")</p>
            </textarea>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">
            Ảnh bìa:
        </label>
        <div class="col-md-10">
            <input type="file" name="fFileUpload" />
            <img src="~/Asset/Images/@Model.Images" width="120">
            (Ảnh hiện tại)
        </div>
    </div>
    <div class="form-group">

        <label class="control-label col-md-2">
            Ngày sửa đổi:
        </label>
        <div class="col-md-10">
            <input type="date" name="dNgaySuaDoi" required />
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Khóa học:</label>
        <div class="col-md-10">
            @Html.DropDownList("MaCD")
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Nhà hợp tác:</label>
        <div class="col-md-10">
            @Html.DropDownList("MaNXB")
        </div>
    </div> <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="LƯU THÔNG TIN" class="btn btn-success" />
        </div>
    </div>
</div>
}
<div>
    @Html.ActionLink("VỀ TRANG QUẢN LÝ SÁCH", "Index")
</div>

ITSupport/Areas/Admin/Views/Course/Index.cshtml
@using ITSupport.Models
@using PagedList.Mvc
@model PagedList.PagedList<ITSupport.Models.Course>

@helper Truncate(string input, int length)
{
    if (input.Length <= length)
    {
        @Html.Raw(input)
    }
    else
    {
        var thisString = input.Substring(0, length);
        @Html.Raw(thisString)
    }
}


@{
    ViewBag.Title = "Quản Lý Thông Tin Chương";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


<h2 style="text-align: center">QUẢN LÝ THÔNG TIN CHƯƠNG</h2>

<p>
    @Html.ActionLink("Thêm mới", "Create")
</p>
<div class="d-flex">
    <form ng-submit="loadData()" class="ml-auto">
        <input class="form-control" placeholder="Từ khóa tìm kiếm..." type="search" ng-model="search" />
    </form>
</div>
<table class="table">
    <tr>
        <th style="text-align:center;width:140px">
            Tên Khóa Học
        </th>
        @*<th style="text-align:center;width:200px">
            Mô tả
        </th>*@
        <th style="text-align:center;width:200px">
            Hình minh hoạ
        </th>
        <th style="text-align:center;width:100px">
            Ngày Tạo
        </th>
        <th style="text-align:center;width:80px">
            Người Tạo
        </th>
        <th style="text-align:center;width:100px">
            Ngày Sửa đổi
        </th>
        <th style="text-align:center;width:100px">
            Chủ đề
        </th>
        <th style="text-align:center;width:100px">
            Nhà xuất bản
        </th>
        <th style="text-align:center">
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <td>
                @*Sử dụng helper để cắt TenSach lấy 50 ký tự*@
                @Truncate(item.Name, 50)
            </td>

            <!--<td>-->
                @*Sử dụng helper để cắt MoTa lấy 70 ký tự*@
                <!--@Html.Raw(Truncate(item.Describe, 70).ToString())
            </td>-->
            <td>
                <img src="~/Asset/Image/@item.Images" asp-append-version="true" style="width: 130px;" />
            </td>
            <td>
                @*Định dạng hiển thị*@
                @Html.FormatValue(@item.CreateDate, "{0:dd/MM/yyyy}")
            </td>
            <td>
                @*Định dạng hiển thị*@
                @*@Truncate(item.CreateBy, 50)*@
                @Html.DisplayFor(modelItem => item.ACourse.Role)
            </td>
            <td>
                @Html.FormatValue(@item.ModifiedDate, "{0:dd/MM/yyyy}")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Topic.NameTopic)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PublishingHouse.NamePH)
            </td>

            <td>
                <a href="@Url.Action("Edit", new { id = item.IDCourse })" class="btn btn-warning" role="button">Sửa</a>
                <a href="@Url.Action("Details", new { id = item.IDCourse })" class="btn btn-primary" role="button">Chi tiết</a>
                <a href="@Url.Action("Delete", new { id = item.IDCourse })" class="btn btn-danger" role="button">Xóa</a>
            </td>
        </tr>
    }
</table>

@*Tạo iên kết phần trang*@
                Trang @(Model.PageCount < Model.PageNumber ? 0 :
        Model.PageNumber)/@Model.PageCount
        <div class="MenuTrang">
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
        </div>
        <style>
            .MenuTrang {
                display: inline;
                text-align: center;
            }
        </style>